Algoritmo "maiorIdades"

Var
contador, idade: inteiro
nome: caracter

Inicio
contador<- 0

enquanto (contador < 5 ) faça
          escreval("digite seu nome")
          leia(nome)
         escreval("digite sua idade")
         leia(idade)
         
         contador<- contador + 1

se idade >= 18 entao
    escreval(nome ," é maior de idade ")
senao
     escreval(nome ," é menor de idade ")
fimse


fimenquanto



Fimalgoritmo