Algoritmo "provadiagnóstica"

Var
numero:  INTEIRO



Inicio
escreval("DIGITE UM NUMERO")
leia(numero)

se numero % 2 = 0 entao
   escreval(" o número " , numero , " é par")
senao
     escreval(" o número " , numero , " é impar")
fimse

se numero < 0 entao
   escreval(" o número " , numero , " é negativo")
senao
     escreval(" o número " , numero , " é positivo")
fimse


Fimalgoritmo